id: AE99D0E80
title: 'The Staircase Ascending to Khecara: A Praise in Accord with the Arrangement
  of the Realm of Holy Nāro Khecarī'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:01:11.824049
  last_modified_at: 2022-03-01 01:01:11.824055
