id: AE99D0E80
title: 'The Method of Accomplishment of Ārya Avalokiteśvara: The Practice of Great
  Compassion & Mahāmudrā in Union'
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-03-01 01:01:11.820954
  last_modified_at: 2022-03-01 01:01:11.820961
